// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://figgrocogufwjturvfdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZ2dyb2NvZ3Vmd2p0dXJ2ZmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMTQyMTUsImV4cCI6MjA1NTU5MDIxNX0.gGijg0jks384EAMlgu0m5NU8iRlsTMEhNVVEZhncjr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);